### ISSUE TITLE
Child widget sizing issue when inside Column wrapped with InstrinsicWidth

### ISSUE THREAD

**Issue by MilesZoltak** [yako-dev/flutter_badges#43] opened 2021-01-17 22:36 UTC
I have several screen with buttons inside of a column, I wrap the column with an InstrinsicWidth widget to make all the buttons expand to fill the width of the column and be uniform and flexible.  When I wrap a button with a badge widget, the badge fits successfully fills out the column, but the button widget itself does not.
![image](https://user-images.githubusercontent.com/40676578/104857998-1b0a4880-58d1-11eb-93a8-d197ef07933a.png)

I'm not sure if the image is gonna be viewable, but that is an example of what I am talking about.  Is this a known issue or am I doing something wrong?

**Comment by Pielgrin** [comment] 2021-05-08 11:19
Hello @MilesZoltak, I have the same issue https://github.com/yako-dev/flutter_badges/issues/51.
To show the badge on the button, the plugin wraps these two widgets inside a Stack widget. The problem is that the plugin does not take as a parameter the possibility to change the fit property of the Stack widget.
To display the button properly, you need to set the fit property to **StackFit. passthrough.**
I made a pull request to have a new parameter to edit this property https://github.com/yako-dev/flutter_badges/pull/52.

If you hurry, feel free to reuse this code and specify fit property to **StackFit. passthrough** or you can't wait that the pull request is merged !

**Comment by yadaniyil** [comment] 2021-05-13 13:00
@Pielgrin @MilesZoltak PR has been merged, thanks

**Closed by yadaniyil** 2021-05-13 13:00 UTC
